version: 2.1

executors:
  java-11:
    docker:
      - image: circleci/openjdk:11-jdk

orbs:
  gradle: circleci/gradle@2.1.0

commands:
  docker-login:
    description: "Authenticates docker client with GCR"
    steps:
      - run:
          name: Docker auth
          command: docker login -u "${DOCKER_LOGIN}" -p "${DOCKER_PASSWORD}" ${DOCKER_REGISTRY}

jobs:
  Build:
    executor: Java-11
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run: ./gradlew clean build -x test

  Test:
    executor: Java-11
    steps:
      - gradle/test


workflows:
  Checkout-Build-Test:
    jobs:
      - Build
      - Test:
          requires:
            - Build
