version: 2.1

executors:
  java-11:
    docker:
      - image: circleci/openjdk:11-jdk

orbs:
  gradle: circleci/gradle@2.1.0
  docker: circleci/docker@1.0.1

jobs:
  Build:
    executor: java-11
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run: ./gradlew --no-daemon clean build
      - persist_to_workspace:
          root: .
          paths:
            - build/libs/

workflows:
  Build-Publish:
    jobs:
      - Build
      - docker/publish:
          registry: $DOCKER_REGISTRY
          image: $CIRCLE_PROJECT_REPONAME
          context: global
          after_checkout:
            - attach_workspace:
                at: .
          requires:
            - Build
