namespace: staging

ingress:
  enabled: true
  domainName: staging.entur.io

service:
  internal:
    loadBalancerIP: 10.100.10.34

deployment:
  replicaCount: 1

horizontalPodAutoscaler:
  minReplicas: 1
  maxReplicas: 1

PodDisruptionBudget:
  enabled: false