namespace: production

ingress:
  enabled: true
  domainName: entur.io

service:
  internal:
    loadBalancerIP: 10.99.0.127

deployment:
  replicaCount: 2

horizontalPodAutoscaler:
  minReplicas: 1
  maxReplicas: 2