namespace: dev

ingress:
  enabled: true
  loadBalancerIp: 35.205.170.68 # kubectl get svc -n kube-system (the external ip of service named traefik-apigee)
  domainName: dev.entur.io

service:
  internal:
    loadBalancerIP: 10.101.10.21

deployment:
  replicaCount: 1

horizontalPodAutoscaler:
  minReplicas: 1
  maxReplicas: 1

PodDisruptionBudget:
  enabled: false