namespace: dev

ingress:
  enabled: true
  domainName: dev.entur.io

service:
  internal:
    loadBalancerIP: 10.101.10.21

deployment:
  replicaCount: 1

horizontalPodAutoscaler:
  minReplicas: 1
  maxReplicas: 1

PodDisruptionBudget:
  enabled: false