apiVersion: v2
name: lahmu
version: 1.0.0
appVersion: "1.0.0"
description: A Helm chart for the lahmu module
keywords:
  - lahmu
sources:
  - https://github.com/entur/lahmu
maintainers:
  - name: 'team-ror'
    email: team.rutedata@entur.org
dependencies:
  - name: common
    version: 1.6.0
    repository: "https://entur.github.io/helm-charts"