{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    traffic-type: api
    {{- include "common.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
  name: mobility
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: lahmu.{{ .Values.ingress.domainName }}
      http:
        paths:
          - backend:
              serviceName: {{ template "name.name" . }}
              servicePort: {{ .Values.service.externalPort }}
{{- end }}